-- RLS policies are NOT used on standalone Neon.
-- Supabase auth.uid() is not available in this context.
-- Access control is enforced at the application layer by filtering
-- queries using the authenticated user's ID from Supabase Auth.
--
-- This file is kept as a placeholder. If you migrate to Supabase-hosted
-- Postgres in the future, restore the RLS policies here.
