import { Platform, type ViewStyle } from 'react-native';
import { MD3LightTheme, MD3DarkTheme, configureFonts, type MD3Theme } from 'react-native-paper';

// Common Thread brand colors — warm & organic palette
export const colors = {
  primary: {
    50: '#fdf5f3',
    100: '#fbe8e3',
    200: '#f7d0c6',
    300: '#f0ad9a',
    400: '#e77f64',
    500: '#d95f3f',
    600: '#c24830',
    700: '#a03828',
    800: '#843026',
    900: '#6f2b24',
  },
  secondary: {
    50: '#f6f7f4',
    100: '#e9ede3',
    200: '#d4dbc8',
    300: '#b6c3a3',
    400: '#95a87b',
    500: '#7a905d',
    600: '#627449',
    700: '#4e5c3b',
    800: '#414b33',
    900: '#38402e',
  },
  accent: {
    50: '#fdf9f0',
    100: '#faf0d9',
    200: '#f4ddb2',
    300: '#ecc481',
    400: '#e3a74e',
    500: '#d9902b',
    600: '#c17623',
    700: '#a15920',
    800: '#854720',
    900: '#6e3c1e',
  },
  neutral: {
    50: '#fafaf9',
    100: '#f5f5f3',
    200: '#e8e7e3',
    300: '#d6d4ce',
    400: '#b8b5ac',
    500: '#9a968b',
    600: '#7c7870',
    700: '#62605a',
    800: '#4a4944',
    900: '#333230',
  },
  // Warm surface colors (inspired by Waffle)
  surface: {
    warm: '#FDFCFA',
    warmBeige: '#F9F5F1',
  },
} as const;

// Typography — Merriweather (headings) + Inter (body)
const baseFont = {
  fontFamily: 'Inter-Regular',
} as const;

const fontConfig = {
  displayLarge: { ...baseFont, fontFamily: 'Merriweather-Bold', fontSize: 57, lineHeight: 64 },
  displayMedium: { ...baseFont, fontFamily: 'Merriweather-Bold', fontSize: 45, lineHeight: 52 },
  displaySmall: { ...baseFont, fontFamily: 'Merriweather-Bold', fontSize: 36, lineHeight: 44 },
  headlineLarge: { ...baseFont, fontFamily: 'Merriweather-Bold', fontSize: 32, lineHeight: 44 },
  headlineMedium: { ...baseFont, fontFamily: 'Merriweather-Bold', fontSize: 28, lineHeight: 40 },
  headlineSmall: { ...baseFont, fontFamily: 'Merriweather-Regular', fontSize: 24, lineHeight: 34 },
  titleLarge: { ...baseFont, fontFamily: 'Merriweather-Regular', fontSize: 22, lineHeight: 30 },
  titleMedium: { ...baseFont, fontFamily: 'Inter-SemiBold', fontSize: 16, lineHeight: 28 },
  titleSmall: { ...baseFont, fontFamily: 'Inter-SemiBold', fontSize: 14, lineHeight: 22 },
  bodyLarge: { ...baseFont, fontFamily: 'Inter-Regular', fontSize: 16, lineHeight: 28 },
  bodyMedium: { ...baseFont, fontFamily: 'Inter-Regular', fontSize: 14, lineHeight: 24 },
  bodySmall: { ...baseFont, fontFamily: 'Inter-Regular', fontSize: 12, lineHeight: 20 },
  labelLarge: { ...baseFont, fontFamily: 'Inter-Medium', fontSize: 14, lineHeight: 20 },
  labelMedium: { ...baseFont, fontFamily: 'Inter-Medium', fontSize: 12, lineHeight: 16 },
  labelSmall: { ...baseFont, fontFamily: 'Inter-Medium', fontSize: 11, lineHeight: 16 },
};

const fonts = configureFonts({ config: fontConfig });

// Soft shadow presets (inspired by Day One — subtle, warm)
export const shadows: Record<'sm' | 'md' | 'lg', ViewStyle> = Platform.select({
  web: {
    sm: { boxShadow: '0 1px 8px rgba(51, 50, 48, 0.06)' } as ViewStyle,
    md: { boxShadow: '0 4px 20px rgba(51, 50, 48, 0.08)' } as ViewStyle,
    lg: { boxShadow: '0 8px 40px rgba(51, 50, 48, 0.10)' } as ViewStyle,
  },
  default: {
    sm: {
      shadowColor: colors.neutral[900],
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 8,
      elevation: 2,
    },
    md: {
      shadowColor: colors.neutral[900],
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.08,
      shadowRadius: 20,
      elevation: 4,
    },
    lg: {
      shadowColor: colors.neutral[900],
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.1,
      shadowRadius: 40,
      elevation: 8,
    },
  },
})!;

export const lightTheme: MD3Theme = {
  ...MD3LightTheme,
  fonts,
  colors: {
    ...MD3LightTheme.colors,
    primary: colors.primary[500],
    onPrimary: '#ffffff',
    primaryContainer: colors.primary[100],
    onPrimaryContainer: colors.primary[900],
    secondary: colors.secondary[500],
    onSecondary: '#ffffff',
    secondaryContainer: colors.secondary[100],
    onSecondaryContainer: colors.secondary[900],
    tertiary: colors.accent[500],
    onTertiary: '#ffffff',
    tertiaryContainer: colors.accent[100],
    onTertiaryContainer: colors.accent[900],
    error: '#c4432b',
    onError: '#ffffff',
    errorContainer: '#fbe8e3',
    onErrorContainer: '#6f2b24',
    background: colors.neutral[50],
    onBackground: colors.neutral[900],
    surface: colors.surface.warm,
    onSurface: colors.neutral[900],
    surfaceVariant: colors.surface.warmBeige,
    onSurfaceVariant: colors.neutral[700],
    outline: colors.neutral[400],
    outlineVariant: colors.neutral[200],
    inverseSurface: colors.neutral[900],
    inverseOnSurface: colors.neutral[100],
    inversePrimary: colors.primary[300],
    elevation: {
      level0: 'transparent',
      level1: colors.surface.warm,
      level2: colors.surface.warmBeige,
      level3: colors.neutral[100],
      level4: colors.neutral[100],
      level5: colors.neutral[200],
    },
    surfaceDisabled: `${colors.neutral[900]}1F`,
    onSurfaceDisabled: `${colors.neutral[900]}61`,
    backdrop: `${colors.neutral[900]}80`,
    shadow: colors.neutral[900],
    scrim: colors.neutral[900],
  },
};

export const darkTheme: MD3Theme = {
  ...MD3DarkTheme,
  fonts,
  colors: {
    ...MD3DarkTheme.colors,
    primary: colors.primary[300],
    onPrimary: colors.primary[900],
    primaryContainer: colors.primary[800],
    onPrimaryContainer: colors.primary[100],
    secondary: colors.secondary[300],
    onSecondary: colors.secondary[900],
    secondaryContainer: colors.secondary[800],
    onSecondaryContainer: colors.secondary[100],
    tertiary: colors.accent[300],
    onTertiary: colors.accent[900],
    tertiaryContainer: colors.accent[800],
    onTertiaryContainer: colors.accent[100],
    error: '#f0ad9a',
    onError: '#6f2b24',
    errorContainer: '#843026',
    onErrorContainer: '#fbe8e3',
    background: colors.neutral[900],
    onBackground: colors.neutral[100],
    surface: colors.neutral[800],
    onSurface: colors.neutral[100],
    surfaceVariant: colors.neutral[700],
    onSurfaceVariant: colors.neutral[300],
    outline: colors.neutral[500],
    outlineVariant: colors.neutral[700],
    inverseSurface: colors.neutral[100],
    inverseOnSurface: colors.neutral[800],
    inversePrimary: colors.primary[600],
    elevation: {
      level0: 'transparent',
      level1: colors.neutral[800],
      level2: colors.neutral[700],
      level3: colors.neutral[700],
      level4: colors.neutral[600],
      level5: colors.neutral[600],
    },
    surfaceDisabled: `${colors.neutral[100]}1F`,
    onSurfaceDisabled: `${colors.neutral[100]}61`,
    backdrop: `${colors.neutral[900]}80`,
    shadow: '#000000',
    scrim: '#000000',
  },
};
